$axure.loadCurrentPage({
  "url":"choice_dept.html",
  "generationDate":new Date(1467363628849.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"username"],
  "page":{
    "packageId":"778b5488fc724d8e98c4df386ac14010",
    "type":"Axure:Page",
    "name":"choice dept",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9a30a92dba9f48adbddbdbaba8420ea0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2d7d071180014c38b40748006bf62620"},
{
          "id":"2cb55e88d1494ebdabf2bf5106242c04",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":44.5,
              "y":130}},
          "adaptiveStyles":{
},
          "masterId":"1ea34248f44d492085137f67760438e1"},
{
          "id":"f762856c3330476382e968ae20d09457",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":172,
              "y":143},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03fc6ff8ecdb4cf8a32fd13368415433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":172,
                  "y":143},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6184193abd843f7be2468bd6ee76ce6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":54,
              "y":200},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa56af256f9a4ecbac03363a82f9aa59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":54,
                  "y":200},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"aee6e80f548d4f68ba4282ef418edf3b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":222},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"6d1704c5d6f94a3e9af153f2472b9a3f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":54,
              "y":242},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9630f7830383441183fbf328de0af884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":54,
                  "y":242},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"6eaf0aa962674ef3b8878af10ea8e546",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":264},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"0b30679b5c2449e78b50853e905b437e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":56,
              "y":284},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a6df59122e3490f89e57912b5c91f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":56,
                  "y":284},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"911191c6be624299bb1270e7ad3dd517",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":306},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"7045685b72444ed3b3e5c274fb618123",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":56,
              "y":326},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"618dd13bb9d045078f25f3ade377e655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":56,
                  "y":326},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"a634d028a5c849b5843363eb49ec0f3b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":348},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"da2be7793e11447fa4e07fe1aa2f74d4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":55,
              "y":368},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9cbe692e2b54c19957018f4f7dbb7d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":55,
                  "y":368},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"0aa14b96ac4b4afcb15118a266dfc704",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":390},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"986319864aa846edbd555cd0315c479f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":55,
              "y":410},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8eb7bd10eef47cb8eb0bc57ce7a4b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":55,
                  "y":410},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"8d7f6bdef144423b8a7c4d1a36a83a34",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":432},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"a18acbedc80b4beea51a84f48714a814",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":452},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baac56dbca034d54ab137e7292b3353b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":452},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"37156b6459a04cd88bbe789013f9f45f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":474},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"0bacd6febf324b60a150f3850a9b16cb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":57,
              "y":494},
            "size":{
              "width":336,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f608e8c60d5f415db796a7407e4ec5a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":57,
                  "y":494},
                "size":{
                  "width":336,
                  "height":22}},
              "adaptiveStyles":{
}}]},
{
          "id":"8dde4d325f2b42b1938b8fc100a59256",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":516},
            "size":{
              "width":356,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/choice_dept/u17_line.png"}},
{
          "id":"23495bb2a8fd49f2a9a3c48624c49145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6699FF},
            "location":{
              "x":44,
              "y":660},
            "size":{
              "width":359,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78515fe89caa46d9b28ad9cd6ae72559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6699FF},
                "location":{
                  "x":44,
                  "y":660},
                "size":{
                  "width":359,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"确认按钮点击时",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/choice_dept/u39.png"}},
{
          "id":"0464b425168541b7b973b0df517ddc8f",
          "label":"backImage1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":54,
              "y":140},
            "size":{
              "width":36,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1149f6d10874b4ab5e50cd43e3ec70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":54,
                  "y":140},
                "size":{
                  "width":36,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"选择科室返回按钮",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/choice_dept/backimage1_u41.png"}}]}},
  "masters":{
    "2d7d071180014c38b40748006bf62620":{
      "packageId":"2d7d071180014c38b40748006bf62620",
      "type":"Axure:Master",
      "name":"phone",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d99712befac24279b86a34aae3f33907",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":429,
                "height":839},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dabd537881e345b2b281223650e11a9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":10,
                    "y":0},
                  "size":{
                    "width":429,
                    "height":839},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}},
{
            "id":"f5852b1d91914e1a8d59b0e4edf121c0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":105},
              "size":{
                "width":360,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"030da254b08b4dd5aab2d7d95f4f332f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":105},
                  "size":{
                    "width":360,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u3.png"}},
{
            "id":"9e71f397c87f4f62a605868be6c8312d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":699},
              "size":{
                "width":360,
                "height":48},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24b95faa0fb44d3ab597259c3c24d1f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":699},
                  "size":{
                    "width":360,
                    "height":48},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u5.png"}},
{
            "id":"26b91ea1ca154fdca046593f0212a0ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFF7F7F7},
{
                    "color":0xFFF7F7F7}]},
              "location":{
                "x":44,
                "y":129},
              "size":{
                "width":360,
                "height":570},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47bd1d8a565c48b29534a6b0c7960e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFF7F7F7},
{
                        "color":0xFFF7F7F7}]},
                  "location":{
                    "x":44,
                    "y":129},
                  "size":{
                    "width":360,
                    "height":570},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u7.png"}}]}},
    "1ea34248f44d492085137f67760438e1":{
      "packageId":"1ea34248f44d492085137f67760438e1",
      "type":"Axure:Master",
      "name":"title bar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d750205dfa844b70b5b3ad869389d788",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"896d8fd6c6064b03a75ffed395618908",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[]}]},
{
            "id":"1c28d63618b14ffbbdc34c128b91e493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF009DD9},
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f2b8ec27df740dd90020671b0016766",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF009DD9},
                  "size":{
                    "width":360,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/choice_dept/u11.png"}}]}}},
  "objectPaths":{
    "9a30a92dba9f48adbddbdbaba8420ea0":{
      "scriptId":"u0",
      "d99712befac24279b86a34aae3f33907":{
        "scriptId":"u1"},
      "dabd537881e345b2b281223650e11a9a":{
        "scriptId":"u2"},
      "f5852b1d91914e1a8d59b0e4edf121c0":{
        "scriptId":"u3"},
      "030da254b08b4dd5aab2d7d95f4f332f":{
        "scriptId":"u4"},
      "9e71f397c87f4f62a605868be6c8312d":{
        "scriptId":"u5"},
      "24b95faa0fb44d3ab597259c3c24d1f6":{
        "scriptId":"u6"},
      "26b91ea1ca154fdca046593f0212a0ca":{
        "scriptId":"u7"},
      "47bd1d8a565c48b29534a6b0c7960e69":{
        "scriptId":"u8"}},
    "2cb55e88d1494ebdabf2bf5106242c04":{
      "scriptId":"u9",
      "d750205dfa844b70b5b3ad869389d788":{
        "scriptId":"u10"},
      "1c28d63618b14ffbbdc34c128b91e493":{
        "scriptId":"u11"},
      "5f2b8ec27df740dd90020671b0016766":{
        "scriptId":"u12"}},
    "f762856c3330476382e968ae20d09457":{
      "scriptId":"u13"},
    "03fc6ff8ecdb4cf8a32fd13368415433":{
      "scriptId":"u14"},
    "d6184193abd843f7be2468bd6ee76ce6":{
      "scriptId":"u15"},
    "fa56af256f9a4ecbac03363a82f9aa59":{
      "scriptId":"u16"},
    "aee6e80f548d4f68ba4282ef418edf3b":{
      "scriptId":"u17"},
    "6d1704c5d6f94a3e9af153f2472b9a3f":{
      "scriptId":"u18"},
    "9630f7830383441183fbf328de0af884":{
      "scriptId":"u19"},
    "6eaf0aa962674ef3b8878af10ea8e546":{
      "scriptId":"u20"},
    "0b30679b5c2449e78b50853e905b437e":{
      "scriptId":"u21"},
    "5a6df59122e3490f89e57912b5c91f0c":{
      "scriptId":"u22"},
    "911191c6be624299bb1270e7ad3dd517":{
      "scriptId":"u23"},
    "7045685b72444ed3b3e5c274fb618123":{
      "scriptId":"u24"},
    "618dd13bb9d045078f25f3ade377e655":{
      "scriptId":"u25"},
    "a634d028a5c849b5843363eb49ec0f3b":{
      "scriptId":"u26"},
    "da2be7793e11447fa4e07fe1aa2f74d4":{
      "scriptId":"u27"},
    "f9cbe692e2b54c19957018f4f7dbb7d7":{
      "scriptId":"u28"},
    "0aa14b96ac4b4afcb15118a266dfc704":{
      "scriptId":"u29"},
    "986319864aa846edbd555cd0315c479f":{
      "scriptId":"u30"},
    "a8eb7bd10eef47cb8eb0bc57ce7a4b4a":{
      "scriptId":"u31"},
    "8d7f6bdef144423b8a7c4d1a36a83a34":{
      "scriptId":"u32"},
    "a18acbedc80b4beea51a84f48714a814":{
      "scriptId":"u33"},
    "baac56dbca034d54ab137e7292b3353b":{
      "scriptId":"u34"},
    "37156b6459a04cd88bbe789013f9f45f":{
      "scriptId":"u35"},
    "0bacd6febf324b60a150f3850a9b16cb":{
      "scriptId":"u36"},
    "f608e8c60d5f415db796a7407e4ec5a2":{
      "scriptId":"u37"},
    "8dde4d325f2b42b1938b8fc100a59256":{
      "scriptId":"u38"},
    "23495bb2a8fd49f2a9a3c48624c49145":{
      "scriptId":"u39"},
    "78515fe89caa46d9b28ad9cd6ae72559":{
      "scriptId":"u40"},
    "0464b425168541b7b973b0df517ddc8f":{
      "scriptId":"u41"},
    "c1149f6d10874b4ab5e50cd43e3ec70a":{
      "scriptId":"u42"}}});