$axure.loadCurrentPage({
  "url":"出入病区核对手术.html",
  "generationDate":new Date(1467783357973.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"username",
"account",
"home",
"dept"],
  "page":{
    "packageId":"1baff7506a9a4e4f965d5be09482b84a",
    "type":"Axure:Page",
    "name":"出入病区核对手术",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"801645debfa3466fb76754b75e0ccfdb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"2d7d071180014c38b40748006bf62620"},
{
          "id":"78c163e4c27842acbd72399d18d60149",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":140}},
          "adaptiveStyles":{
},
          "masterId":"1ea34248f44d492085137f67760438e1"},
{
          "id":"ef6e7f1233cf49e794bb86af8f0ed3c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":154,
              "y":153},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c0e1a3b9c649a38e095a25475d2e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":153},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fc3c2fa358e49ec8b271ac1f2c22d31",
          "label":"出入病区返回按钮",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":64,
              "y":150},
            "size":{
              "width":36,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"281eb5a3ceb74d5e95dd5f6bd7b0764f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":64,
                  "y":150},
                "size":{
                  "width":36,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"单击1<br> (If state of 出入病区核对手术面板 等于 手术信息确认)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["37f8938bcb6340358e51c96e5b7a8a56"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["37f8938bcb6340358e51c96e5b7a8a56"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 出入病区核对手术面板 to 核对手术扫描腕带 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["37f8938bcb6340358e51c96e5b7a8a56"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"单击2<br> (Else If state of 出入病区核对手术面板 等于 核对手术扫描腕带)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["37f8938bcb6340358e51c96e5b7a8a56"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["37f8938bcb6340358e51c96e5b7a8a56"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 home = &quot;home&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"home"},
{
                                "exprType":"stringLiteral",
                                "value":"home",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/backimage1_u57.png"}},
{
          "id":"37f8938bcb6340358e51c96e5b7a8a56",
          "label":"出入病区核对手术面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":190},
            "size":{
              "width":360,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43d79f7fe8d54333b0fdde9087caa017",
              "label":"核对手术扫描腕带",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"09e4d290201346f4aaec7528c53407dc",
                  "label":"巡视扫描腕带按钮",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":190,
                      "y":480},
                    "size":{
                      "width":170,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87ad967310d64336b87858286eb6553c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":190,
                          "y":480},
                        "size":{
                          "width":170,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"巡视扫描腕带",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 核对手术进度条",
                              "objectsToFades":[{
                                  "objectPath":["f08eeda280a247e58e3e4457a3b2ac61"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待2000毫秒",
                              "waitTime":2000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 核对手术进度条",
                              "objectsToFades":[{
                                  "objectPath":["f08eeda280a247e58e3e4457a3b2ac61"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 出入病区核对手术面板 to 手术信息确认 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["37f8938bcb6340358e51c96e5b7a8a56"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/生命体征采集/生命体征扫描腕带按钮_u20.png"}}]},
{
              "id":"0ff83fa3e4c54c518113f70fd1e9ee8f",
              "label":"手术信息确认",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"147690b662954ae285efd35163ff6e62",
                  "label":"巡视确定按钮",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":0,
                      "y":480},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a08dbb9242342fc9f1c2b4e3b41edc6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":0,
                          "y":480},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"巡视确定按钮",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]},
{
                              "action":"wait",
                              "description":"等待2000毫秒",
                              "waitTime":2000},
{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]},
{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/login/u55.png"}},
{
                  "id":"9a07b3e856cc4f3f860c901a903f3710",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4}]},
                    "location":{
                      "x":0,
                      "y":105},
                    "size":{
                      "width":360,
                      "height":42},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6630cf1acd2d4759b49e5a70099a985b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]},
                        "location":{
                          "x":0,
                          "y":105},
                        "size":{
                          "width":360,
                          "height":42},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/出入病区核对手术/u22.png"}},
{
                  "id":"9d6d849519d64b7393c66c52fb29b281",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":24,
                      "y":118},
                    "size":{
                      "width":65,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"710bf25a8d894a3bbcdcb608ca7f67fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":24,
                          "y":118},
                        "size":{
                          "width":65,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8e6c3075c53f4423840454c60c26acc0",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":0,
                      "y":147},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"364bedf96d644930aacac79312354bc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":0,
                          "y":147},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/出入病区核对手术/u26.png"}},
{
                  "id":"73cc36c2c9be4e9a858e897e92ad652a",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":0,
                      "y":187},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8591b4524b2c4078a2073f5839bd3db0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":0,
                          "y":187},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/出入病区核对手术/u28.png"}},
{
                  "id":"8dc628cb29f44212b1bbe886a1ad040e",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":0,
                      "y":227},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f77e4d5b04db4dbd9732c0cbfb78e9d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":0,
                          "y":227},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/出入病区核对手术/u28.png"}},
{
                  "id":"4425698bded148d4ae8d31c4db5bd0d5",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":0,
                      "y":267},
                    "size":{
                      "width":360,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d986907beffa41118828d03e7b6a345e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":0,
                          "y":267},
                        "size":{
                          "width":360,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/出入病区核对手术/u28.png"}},
{
                  "id":"be22e452b3474111929ba2d80967326e",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":147},
                    "size":{
                      "width":10,
                      "height":160},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/出入病区核对手术/u34_line.png"}},
{
                  "id":"8c9a754b8b7f4f1e9d1b6f8525ab453e",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":36,
                      "y":159},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"237442871d114a80b78396ef542eef63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":36,
                          "y":159},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f0d4c466527498ba6de0fb8f1d97b14",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":36,
                      "y":197},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cab0bfc25922499eab0e9c8f6a23dcca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":36,
                          "y":197},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3486081049849f794727cab0519a075",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":36,
                      "y":239},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f799c30454b46a88faec4e2d79b33da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":36,
                          "y":239},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"293f448f41de4a8bb8a036fed7bbd445",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":36,
                      "y":279},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"479c976ea27b4bd0b2ee10188158ece2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":36,
                          "y":279},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"951f39402dfc4fce85ae04f582185c31",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":137,
                      "y":197},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1273b51f36244d18588071c5977a209",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":137,
                          "y":197},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"645173276b204430bdd7dd0083a0ab95",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":137,
                      "y":159},
                    "size":{
                      "width":101,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e96159a5e564e719c3d441a1a42c8f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":137,
                          "y":159},
                        "size":{
                          "width":101,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1b029281adc445499c6d8fa5fd02496a",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":137,
                      "y":239},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d28bb358248145158d63209b41c8ce4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":137,
                          "y":239},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"838a83686cb94717a09e426fb5058e27",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":137,
                      "y":279},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99b90e2a7e1041a2a4d520a257cb5697",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":137,
                          "y":279},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e74849915d24c62ba9db66fed4382b1",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":5,
                      "y":5},
                    "size":{
                      "width":95,
                      "height":95}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"856ff7c64ca443c8806d138067decebc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":5,
                          "y":5},
                        "size":{
                          "width":95,
                          "height":95}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/login_icon_u12.png"}},
{
                  "id":"7205d57c7fdd4d63844ef336695e32fc",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":14},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d49b67c0773e4384ae1326ede3aca230",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":14},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c53bb03efae430f9f60ca9a33944661",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":220,
                      "y":14},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a950b685c9d945a990ebdbbd9df32e25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":220,
                          "y":14},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"48315d8879ae4f65afc35b06f5ad42fd",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":45},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33ad4c39cb36457c94af6e7288daea89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":45},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a65fe7facd124da18126c2bdc2f88b2b",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":185,
                      "y":14},
                    "size":{
                      "width":14,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f164bb8f2f7403a946ee6c578d2b081",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":185,
                          "y":14},
                        "size":{
                          "width":14,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f800c56d288e4c13ba035a1b03060deb",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":167,
                      "y":45},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a5af8b89b4e436c994205d0d78d9a9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":167,
                          "y":45},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7717480a7b194be89a600d1950fd34d3",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":220,
                      "y":45},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7996f35ed0244bdba8bd1f0b82201f6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":220,
                          "y":45},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"28fd23441078434c9ed044827dfe25df",
                  "label":"",
                  "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":74},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4baaed208d2347c9866949a142546272",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"37f8938bcb6340358e51c96e5b7a8a56",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":74},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"f08eeda280a247e58e3e4457a3b2ac61",
          "label":"核对手术进度条",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":432},
            "size":{
              "width":36,
              "height":36},
            "visible":false,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5c22d8c3304befbbbfc3e6bad30755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":432},
                "size":{
                  "width":36,
                  "height":36},
                "visible":false,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/登录进度条_u59.gif"}},
{
          "id":"deb3719f6db340fcaa4fad79d001fc04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":352,
              "y":149},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2d0b991c914d9fb6b605a038acdbf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":149},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcaef1f3882040e1bd43a819d4c8ed08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":169},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da3f5ba165d74a1ba0e391bb09e20081",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":169},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2d7d071180014c38b40748006bf62620":{
      "packageId":"2d7d071180014c38b40748006bf62620",
      "type":"Axure:Master",
      "name":"phone",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d99712befac24279b86a34aae3f33907",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":429,
                "height":839},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dabd537881e345b2b281223650e11a9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":10,
                    "y":0},
                  "size":{
                    "width":429,
                    "height":839},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}},
{
            "id":"f5852b1d91914e1a8d59b0e4edf121c0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":105},
              "size":{
                "width":360,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"030da254b08b4dd5aab2d7d95f4f332f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":105},
                  "size":{
                    "width":360,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u3.png"}},
{
            "id":"9e71f397c87f4f62a605868be6c8312d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":699},
              "size":{
                "width":360,
                "height":48},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24b95faa0fb44d3ab597259c3c24d1f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":699},
                  "size":{
                    "width":360,
                    "height":48},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u5.png"}},
{
            "id":"26b91ea1ca154fdca046593f0212a0ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFF7F7F7},
{
                    "color":0xFFF7F7F7}]},
              "location":{
                "x":44,
                "y":129},
              "size":{
                "width":360,
                "height":570},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47bd1d8a565c48b29534a6b0c7960e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFF7F7F7},
{
                        "color":0xFFF7F7F7}]},
                  "location":{
                    "x":44,
                    "y":129},
                  "size":{
                    "width":360,
                    "height":570},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u7.png"}}]}},
    "1ea34248f44d492085137f67760438e1":{
      "packageId":"1ea34248f44d492085137f67760438e1",
      "type":"Axure:Master",
      "name":"title bar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d750205dfa844b70b5b3ad869389d788",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"896d8fd6c6064b03a75ffed395618908",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[]}]},
{
            "id":"1c28d63618b14ffbbdc34c128b91e493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF009DD9},
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f2b8ec27df740dd90020671b0016766",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF009DD9},
                  "size":{
                    "width":360,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u27.png"}}]}}},
  "objectPaths":{
    "801645debfa3466fb76754b75e0ccfdb":{
      "scriptId":"u0",
      "d99712befac24279b86a34aae3f33907":{
        "scriptId":"u1"},
      "dabd537881e345b2b281223650e11a9a":{
        "scriptId":"u2"},
      "f5852b1d91914e1a8d59b0e4edf121c0":{
        "scriptId":"u3"},
      "030da254b08b4dd5aab2d7d95f4f332f":{
        "scriptId":"u4"},
      "9e71f397c87f4f62a605868be6c8312d":{
        "scriptId":"u5"},
      "24b95faa0fb44d3ab597259c3c24d1f6":{
        "scriptId":"u6"},
      "26b91ea1ca154fdca046593f0212a0ca":{
        "scriptId":"u7"},
      "47bd1d8a565c48b29534a6b0c7960e69":{
        "scriptId":"u8"}},
    "78c163e4c27842acbd72399d18d60149":{
      "scriptId":"u9",
      "d750205dfa844b70b5b3ad869389d788":{
        "scriptId":"u10"},
      "1c28d63618b14ffbbdc34c128b91e493":{
        "scriptId":"u11"},
      "5f2b8ec27df740dd90020671b0016766":{
        "scriptId":"u12"}},
    "ef6e7f1233cf49e794bb86af8f0ed3c7":{
      "scriptId":"u13"},
    "43c0e1a3b9c649a38e095a25475d2e5a":{
      "scriptId":"u14"},
    "0fc3c2fa358e49ec8b271ac1f2c22d31":{
      "scriptId":"u15"},
    "281eb5a3ceb74d5e95dd5f6bd7b0764f":{
      "scriptId":"u16"},
    "37f8938bcb6340358e51c96e5b7a8a56":{
      "scriptId":"u17"},
    "09e4d290201346f4aaec7528c53407dc":{
      "scriptId":"u18"},
    "87ad967310d64336b87858286eb6553c":{
      "scriptId":"u19"},
    "147690b662954ae285efd35163ff6e62":{
      "scriptId":"u20"},
    "3a08dbb9242342fc9f1c2b4e3b41edc6":{
      "scriptId":"u21"},
    "9a07b3e856cc4f3f860c901a903f3710":{
      "scriptId":"u22"},
    "6630cf1acd2d4759b49e5a70099a985b":{
      "scriptId":"u23"},
    "9d6d849519d64b7393c66c52fb29b281":{
      "scriptId":"u24"},
    "710bf25a8d894a3bbcdcb608ca7f67fc":{
      "scriptId":"u25"},
    "8e6c3075c53f4423840454c60c26acc0":{
      "scriptId":"u26"},
    "364bedf96d644930aacac79312354bc0":{
      "scriptId":"u27"},
    "73cc36c2c9be4e9a858e897e92ad652a":{
      "scriptId":"u28"},
    "8591b4524b2c4078a2073f5839bd3db0":{
      "scriptId":"u29"},
    "8dc628cb29f44212b1bbe886a1ad040e":{
      "scriptId":"u30"},
    "f77e4d5b04db4dbd9732c0cbfb78e9d5":{
      "scriptId":"u31"},
    "4425698bded148d4ae8d31c4db5bd0d5":{
      "scriptId":"u32"},
    "d986907beffa41118828d03e7b6a345e":{
      "scriptId":"u33"},
    "be22e452b3474111929ba2d80967326e":{
      "scriptId":"u34"},
    "8c9a754b8b7f4f1e9d1b6f8525ab453e":{
      "scriptId":"u35"},
    "237442871d114a80b78396ef542eef63":{
      "scriptId":"u36"},
    "9f0d4c466527498ba6de0fb8f1d97b14":{
      "scriptId":"u37"},
    "cab0bfc25922499eab0e9c8f6a23dcca":{
      "scriptId":"u38"},
    "f3486081049849f794727cab0519a075":{
      "scriptId":"u39"},
    "1f799c30454b46a88faec4e2d79b33da":{
      "scriptId":"u40"},
    "293f448f41de4a8bb8a036fed7bbd445":{
      "scriptId":"u41"},
    "479c976ea27b4bd0b2ee10188158ece2":{
      "scriptId":"u42"},
    "951f39402dfc4fce85ae04f582185c31":{
      "scriptId":"u43"},
    "d1273b51f36244d18588071c5977a209":{
      "scriptId":"u44"},
    "645173276b204430bdd7dd0083a0ab95":{
      "scriptId":"u45"},
    "3e96159a5e564e719c3d441a1a42c8f0":{
      "scriptId":"u46"},
    "1b029281adc445499c6d8fa5fd02496a":{
      "scriptId":"u47"},
    "d28bb358248145158d63209b41c8ce4e":{
      "scriptId":"u48"},
    "838a83686cb94717a09e426fb5058e27":{
      "scriptId":"u49"},
    "99b90e2a7e1041a2a4d520a257cb5697":{
      "scriptId":"u50"},
    "4e74849915d24c62ba9db66fed4382b1":{
      "scriptId":"u51"},
    "856ff7c64ca443c8806d138067decebc":{
      "scriptId":"u52"},
    "7205d57c7fdd4d63844ef336695e32fc":{
      "scriptId":"u53"},
    "d49b67c0773e4384ae1326ede3aca230":{
      "scriptId":"u54"},
    "8c53bb03efae430f9f60ca9a33944661":{
      "scriptId":"u55"},
    "a950b685c9d945a990ebdbbd9df32e25":{
      "scriptId":"u56"},
    "48315d8879ae4f65afc35b06f5ad42fd":{
      "scriptId":"u57"},
    "33ad4c39cb36457c94af6e7288daea89":{
      "scriptId":"u58"},
    "a65fe7facd124da18126c2bdc2f88b2b":{
      "scriptId":"u59"},
    "2f164bb8f2f7403a946ee6c578d2b081":{
      "scriptId":"u60"},
    "f800c56d288e4c13ba035a1b03060deb":{
      "scriptId":"u61"},
    "5a5af8b89b4e436c994205d0d78d9a9c":{
      "scriptId":"u62"},
    "7717480a7b194be89a600d1950fd34d3":{
      "scriptId":"u63"},
    "7996f35ed0244bdba8bd1f0b82201f6b":{
      "scriptId":"u64"},
    "28fd23441078434c9ed044827dfe25df":{
      "scriptId":"u65"},
    "4baaed208d2347c9866949a142546272":{
      "scriptId":"u66"},
    "f08eeda280a247e58e3e4457a3b2ac61":{
      "scriptId":"u67"},
    "8c5c22d8c3304befbbbfc3e6bad30755":{
      "scriptId":"u68"},
    "deb3719f6db340fcaa4fad79d001fc04":{
      "scriptId":"u69"},
    "fa2d0b991c914d9fb6b605a038acdbf0":{
      "scriptId":"u70"},
    "bcaef1f3882040e1bd43a819d4c8ed08":{
      "scriptId":"u71"},
    "da3f5ba165d74a1ba0e391bb09e20081":{
      "scriptId":"u72"}}});