$axure.loadCurrentPage({
  "url":"生命体征采集.html",
  "generationDate":new Date(1467783357349.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"username",
"account",
"home",
"dept"],
  "page":{
    "packageId":"8e833e10aa464918bb8fa9b8ba6fc44b",
    "type":"Axure:Page",
    "name":"生命体征采集",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b06dd1b25b544af182a0959d19c47a5d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"2d7d071180014c38b40748006bf62620"},
{
          "id":"993dbe542d8241c5baff795011d3874d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":140}},
          "adaptiveStyles":{
},
          "masterId":"1ea34248f44d492085137f67760438e1"},
{
          "id":"bd93f9af3fb6476bb590ffca876cf3f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":174,
              "y":153},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d91c5af4452413cb270e2debe7a9670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":174,
                  "y":153},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3fb47aacf05422fb73092fb760cf0b9",
          "label":"生命体征采集返回按钮",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":64,
              "y":150},
            "size":{
              "width":36,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43714723188944d3888cbd7709decaf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":64,
                  "y":150},
                "size":{
                  "width":36,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"单击时<br> (If state of 生命体征面板 等于 扫描腕带)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["88a058895abb4044b05dbedcf938dab8"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["88a058895abb4044b05dbedcf938dab8"],
                      "panelIndex":0}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 home = &quot;home&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"home"},
{
                                "exprType":"stringLiteral",
                                "value":"home",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"单击2<br> (Else If state of 生命体征面板 等于 录入生命体征)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["88a058895abb4044b05dbedcf938dab8"]}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["88a058895abb4044b05dbedcf938dab8"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 生命体征面板 to 扫描腕带 显示隐藏",
                      "panelsToStates":[{
                          "panelPath":["88a058895abb4044b05dbedcf938dab8"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/backimage1_u57.png"}},
{
          "id":"88a058895abb4044b05dbedcf938dab8",
          "label":"生命体征面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":190},
            "size":{
              "width":360,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9a7d25423173424581e8dc4f0a0e6f37",
              "label":"扫描腕带",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4d141e9d2b97491782aaff43bc73ec87",
                  "label":"扫描腕带",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "size":{
                      "width":360,
                      "height":520},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF99CCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"644903298cb44220800ed14a2ff58d22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "size":{
                          "width":360,
                          "height":520},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF99CCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生命体征采集/扫描腕带_u18.png"}},
{
                  "id":"514b6d31868346a1a7c2dd6df6112fde",
                  "label":"生命体征扫描腕带按钮",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":190,
                      "y":480},
                    "size":{
                      "width":170,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28f9c34245e440b8bff268276531c81a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":190,
                          "y":480},
                        "size":{
                          "width":170,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"生命体征扫描腕带",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 体征采集进度条",
                              "objectsToFades":[{
                                  "objectPath":["b77e6ea4a5294c3f9b054d12c324b64c"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待2000毫秒",
                              "waitTime":2000},
{
                              "action":"setPanelState",
                              "description":"设置 生命体征面板 to 录入生命体征 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["88a058895abb4044b05dbedcf938dab8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 体征采集进度条",
                              "objectsToFades":[{
                                  "objectPath":["b77e6ea4a5294c3f9b054d12c324b64c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/生命体征采集/生命体征扫描腕带按钮_u20.png"}}]},
{
              "id":"d0ccb42124b543dc8bf27ca9cbb8930e",
              "label":"录入生命体征",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aa222094f0cf483b8c37ed1e0892c95a",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":-8,
                      "y":480},
                    "size":{
                      "width":368,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x797979},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af5d662a96b64854b2d5c026055963d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":-8,
                          "y":480},
                        "size":{
                          "width":368,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x797979},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"体温是否为空<br> (If 文字于 体温 等于 &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["e5fba94f4ecb458aa8c2f99aa6fb6285"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to 体温为空 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"脉搏是否为空<br> (Else If 文字于 脉搏 等于 &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["425c0ee90bd749d0aee96d0f8ea48848"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to 脉搏为空 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"呼吸是否为空<br> (Else If 文字于 呼吸 等于 &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["b978aa338cd84e2fbce6792fe71e60ce"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to 呼吸为空 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"心率是否为空<br> (Else If 文字于 心率 等于 &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6c1938598cd44084ac1512eb9ff4aca1"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to 心率为空 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":4,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"全部填写正确<br> (Else If 文字于 体温 ≠ &quot;&quot; 和 文字于 脉搏 ≠ &quot;&quot; 和 文字于 呼吸 ≠ &quot;&quot; 和 文字于 心率 ≠ &quot;&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"&&",
                            "leftExpr":{
                              "exprType":"binaryOp",
                              "op":"!=",
                              "leftExpr":{
                                "exprType":"fcall",
                                "functionName":"GetWidgetText",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["e5fba94f4ecb458aa8c2f99aa6fb6285"]}]},
                              "rightExpr":{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}},
                            "rightExpr":{
                              "exprType":"binaryOp",
                              "op":"&&",
                              "leftExpr":{
                                "exprType":"binaryOp",
                                "op":"!=",
                                "leftExpr":{
                                  "exprType":"fcall",
                                  "functionName":"GetWidgetText",
                                  "arguments":[{
                                      "exprType":"pathLiteral",
                                      "isThis":false,
                                      "isFocused":false,
                                      "isTarget":false,
                                      "value":["425c0ee90bd749d0aee96d0f8ea48848"]}]},
                                "rightExpr":{
                                  "exprType":"stringLiteral",
                                  "value":"",
                                  "stos":[]}},
                              "rightExpr":{
                                "exprType":"binaryOp",
                                "op":"&&",
                                "leftExpr":{
                                  "exprType":"binaryOp",
                                  "op":"!=",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b978aa338cd84e2fbce6792fe71e60ce"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"",
                                    "stos":[]}},
                                "rightExpr":{
                                  "exprType":"binaryOp",
                                  "op":"!=",
                                  "leftExpr":{
                                    "exprType":"fcall",
                                    "functionName":"GetWidgetText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6c1938598cd44084ac1512eb9ff4aca1"]}]},
                                  "rightExpr":{
                                    "exprType":"stringLiteral",
                                    "value":"",
                                    "stos":[]}}}}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to none",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 userInfo",
                              "target":{
                                "targetType":"page",
                                "url":"userinfo.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/生命体征采集/u22.png"}},
{
                  "id":"6f524b99166349be81536052ce06ffbe",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":21,
                      "y":143},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64635a16f2cf4b5ea7ffd310c5728f61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":21,
                          "y":143},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"34862cddb1254e88a4245e4202596b94",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":139,
                      "y":180},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a4fe74743ea422dbe1391e59e8c110b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":139,
                          "y":180},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"97c8c45647ef4f799570e7d41c4d8eb7",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":21,
                      "y":212},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cba566e59ce6454c9df70d6a86b39b29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":21,
                          "y":212},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e1724532151141c6b3da6071d3d6c716",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":21,
                      "y":246},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1155b2d64e54856a3a0e84f16ba40bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":21,
                          "y":246},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"590c483108984bf580825fdf80da7f11",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":21,
                      "y":282},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b407a029ff9451dabec5859293b4864",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":21,
                          "y":282},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0b7d5dd20f8e478183d2aa9e353387bb",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":110,
                      "y":140},
                    "size":{
                      "width":220,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"bcfe04dd91f649609c4c59035ea1354f",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":21,
                      "y":176},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2914550855143849221d5b98ff8e910",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":21,
                          "y":176},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e5fba94f4ecb458aa8c2f99aa6fb6285",
                  "label":"体温",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":109,
                      "y":172},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"获取焦点",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to none",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"425c0ee90bd749d0aee96d0f8ea48848",
                  "label":"脉搏",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":109,
                      "y":207},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"脉搏获取焦点",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to none",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"b978aa338cd84e2fbce6792fe71e60ce",
                  "label":"呼吸",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":109,
                      "y":242},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"呼吸获取焦点",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to none",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"6c1938598cd44084ac1512eb9ff4aca1",
                  "label":"心率",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":109,
                      "y":277},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"心率获取焦点",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 生命体征输入error to none",
                              "panelsToStates":[{
                                  "panelPath":["387445aa9cd04c9a855d77175243eb78"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":5,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"387445aa9cd04c9a855d77175243eb78",
                  "label":"生命体征输入error",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":109,
                      "y":305},
                    "size":{
                      "width":220,
                      "height":24},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"eb789b6af5b049fab4bb6e7a19333afc",
                      "label":"体温为空",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"978870c789494d07ab14fb3c7a716205",
                          "label":"",
                          "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "horizontalAlignment":"right",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":200,
                              "height":24},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c83f67a454c64407b3285c63e624d207",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "horizontalAlignment":"right",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":200,
                                  "height":24},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]},
{
                      "id":"18f0500528ec4adea836b9fda20f452a",
                      "label":"脉搏为空",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"459f2d8031c242d5b1d57e077d2ac330",
                          "label":"",
                          "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "horizontalAlignment":"right",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":200,
                              "height":24},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f904b3bec3624ddbaebd49ecb9ed4ff9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "horizontalAlignment":"right",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":200,
                                  "height":24},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]},
{
                      "id":"eda9ba7bab724ef79972a9b8db2419bb",
                      "label":"呼吸为空",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"9b5938256b3042f8b674d7cdb9812f0f",
                          "label":"",
                          "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "horizontalAlignment":"right",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":200,
                              "height":24},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"16be25b509dd47e08c371ccd31237cdf",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "horizontalAlignment":"right",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":200,
                                  "height":24},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]},
{
                      "id":"872767f4e64646c8bb61fcaf03f284a2",
                      "label":"心率为空",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"843403c8d36d40a8a50f53a70f357f79",
                          "label":"",
                          "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "horizontalAlignment":"right",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":200,
                              "height":24},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0x797979}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"376199f08af1443f8da3951aedd9c287",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"387445aa9cd04c9a855d77175243eb78",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "horizontalAlignment":"right",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "size":{
                                  "width":200,
                                  "height":24},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0x797979}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]},
{
                      "id":"8bb2aa72e7184be8a26bc867fc2217e1",
                      "label":"none",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]},
{
                  "id":"0a2d88eac49c4b2bb189fd6ff49e84dd",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":360,
                      "height":105},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65b49b7f722646d5bc6fd9f8017b6ad9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":360,
                          "height":105},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/生命体征采集/u50.png"}},
{
                  "id":"eea7b431c55548459d9f380482e69566",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":5,
                      "y":5},
                    "size":{
                      "width":95,
                      "height":95}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"27f7ee264c7343dfab008f6239885fed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":5,
                          "y":5},
                        "size":{
                          "width":95,
                          "height":95}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/login/login_icon_u12.png"}},
{
                  "id":"137039dc944e4296877a6a772b9b57b0",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":14},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"320679549c98435d97a40d55caa599cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":14},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4ce7920bfb384c85b7647b80fb455f81",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":220,
                      "y":14},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"340d2f78b8b64d7dacfcd3026b9897b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":220,
                          "y":14},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7463d3755c414169a218db833f15d0db",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":45},
                    "size":{
                      "width":28,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fa57b2b0be146938d057573dfc577f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":45},
                        "size":{
                          "width":28,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e2847f1fb8645aeba1d62881136fef2",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":185,
                      "y":14},
                    "size":{
                      "width":14,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0e3f3bf2c2949a2b689122286aadbea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":185,
                          "y":14},
                        "size":{
                          "width":14,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6aeb8942e1e84c2d80d39e87f063de92",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":220,
                      "y":45},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aaea9b1bd66f458c8b1f80d41e167a1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":220,
                          "y":45},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1c2ca35a1f9d437ba60e9f3fb41538cf",
                  "label":"",
                  "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":120,
                      "y":74},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9a30732de9647f8b7f5604892d2d9d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"88a058895abb4044b05dbedcf938dab8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":120,
                          "y":74},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"b77e6ea4a5294c3f9b054d12c324b64c",
          "label":"体征采集进度条",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":216,
              "y":432},
            "size":{
              "width":36,
              "height":36},
            "visible":false,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b684ee9cc8174cc1a14b53c4c6b1ac19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":216,
                  "y":432},
                "size":{
                  "width":36,
                  "height":36},
                "visible":false,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/登录进度条_u59.gif"}},
{
          "id":"96790fccb6624e3bbb2bdb1767eb7992",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":352,
              "y":149},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b49f5b78f9474a0abddbd4492a930be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":352,
                  "y":149},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3545d0a410841d592bd786b45278c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":346,
              "y":169},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a17f9e89b424c28a95d6c4ae20ea162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":346,
                  "y":169},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "2d7d071180014c38b40748006bf62620":{
      "packageId":"2d7d071180014c38b40748006bf62620",
      "type":"Axure:Master",
      "name":"phone",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d99712befac24279b86a34aae3f33907",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":429,
                "height":839},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dabd537881e345b2b281223650e11a9a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":10,
                    "y":0},
                  "size":{
                    "width":429,
                    "height":839},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}},
{
            "id":"f5852b1d91914e1a8d59b0e4edf121c0",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":105},
              "size":{
                "width":360,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"030da254b08b4dd5aab2d7d95f4f332f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":105},
                  "size":{
                    "width":360,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u3.png"}},
{
            "id":"9e71f397c87f4f62a605868be6c8312d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":44,
                "y":699},
              "size":{
                "width":360,
                "height":48},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24b95faa0fb44d3ab597259c3c24d1f6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":44,
                    "y":699},
                  "size":{
                    "width":360,
                    "height":48},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u5.png"}},
{
            "id":"26b91ea1ca154fdca046593f0212a0ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFE8E8E8},
{
                    "color":0xFFF7F7F7},
{
                    "color":0xFFF7F7F7}]},
              "location":{
                "x":44,
                "y":129},
              "size":{
                "width":360,
                "height":570},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"47bd1d8a565c48b29534a6b0c7960e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFE8E8E8},
{
                        "color":0xFFF7F7F7},
{
                        "color":0xFFF7F7F7}]},
                  "location":{
                    "x":44,
                    "y":129},
                  "size":{
                    "width":360,
                    "height":570},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u7.png"}}]}},
    "1ea34248f44d492085137f67760438e1":{
      "packageId":"1ea34248f44d492085137f67760438e1",
      "type":"Axure:Master",
      "name":"title bar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d750205dfa844b70b5b3ad869389d788",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"896d8fd6c6064b03a75ffed395618908",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[]}]},
{
            "id":"1c28d63618b14ffbbdc34c128b91e493",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFF009DD9},
              "size":{
                "width":360,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5f2b8ec27df740dd90020671b0016766",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF009DD9},
                  "size":{
                    "width":360,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u27.png"}}]}}},
  "objectPaths":{
    "b06dd1b25b544af182a0959d19c47a5d":{
      "scriptId":"u0",
      "d99712befac24279b86a34aae3f33907":{
        "scriptId":"u1"},
      "dabd537881e345b2b281223650e11a9a":{
        "scriptId":"u2"},
      "f5852b1d91914e1a8d59b0e4edf121c0":{
        "scriptId":"u3"},
      "030da254b08b4dd5aab2d7d95f4f332f":{
        "scriptId":"u4"},
      "9e71f397c87f4f62a605868be6c8312d":{
        "scriptId":"u5"},
      "24b95faa0fb44d3ab597259c3c24d1f6":{
        "scriptId":"u6"},
      "26b91ea1ca154fdca046593f0212a0ca":{
        "scriptId":"u7"},
      "47bd1d8a565c48b29534a6b0c7960e69":{
        "scriptId":"u8"}},
    "993dbe542d8241c5baff795011d3874d":{
      "scriptId":"u9",
      "d750205dfa844b70b5b3ad869389d788":{
        "scriptId":"u10"},
      "1c28d63618b14ffbbdc34c128b91e493":{
        "scriptId":"u11"},
      "5f2b8ec27df740dd90020671b0016766":{
        "scriptId":"u12"}},
    "bd93f9af3fb6476bb590ffca876cf3f0":{
      "scriptId":"u13"},
    "5d91c5af4452413cb270e2debe7a9670":{
      "scriptId":"u14"},
    "d3fb47aacf05422fb73092fb760cf0b9":{
      "scriptId":"u15"},
    "43714723188944d3888cbd7709decaf1":{
      "scriptId":"u16"},
    "88a058895abb4044b05dbedcf938dab8":{
      "scriptId":"u17"},
    "4d141e9d2b97491782aaff43bc73ec87":{
      "scriptId":"u18"},
    "644903298cb44220800ed14a2ff58d22":{
      "scriptId":"u19"},
    "514b6d31868346a1a7c2dd6df6112fde":{
      "scriptId":"u20"},
    "28f9c34245e440b8bff268276531c81a":{
      "scriptId":"u21"},
    "aa222094f0cf483b8c37ed1e0892c95a":{
      "scriptId":"u22"},
    "af5d662a96b64854b2d5c026055963d5":{
      "scriptId":"u23"},
    "6f524b99166349be81536052ce06ffbe":{
      "scriptId":"u24"},
    "64635a16f2cf4b5ea7ffd310c5728f61":{
      "scriptId":"u25"},
    "34862cddb1254e88a4245e4202596b94":{
      "scriptId":"u26"},
    "9a4fe74743ea422dbe1391e59e8c110b":{
      "scriptId":"u27"},
    "97c8c45647ef4f799570e7d41c4d8eb7":{
      "scriptId":"u28"},
    "cba566e59ce6454c9df70d6a86b39b29":{
      "scriptId":"u29"},
    "e1724532151141c6b3da6071d3d6c716":{
      "scriptId":"u30"},
    "e1155b2d64e54856a3a0e84f16ba40bd":{
      "scriptId":"u31"},
    "590c483108984bf580825fdf80da7f11":{
      "scriptId":"u32"},
    "2b407a029ff9451dabec5859293b4864":{
      "scriptId":"u33"},
    "0b7d5dd20f8e478183d2aa9e353387bb":{
      "scriptId":"u34"},
    "bcfe04dd91f649609c4c59035ea1354f":{
      "scriptId":"u35"},
    "b2914550855143849221d5b98ff8e910":{
      "scriptId":"u36"},
    "e5fba94f4ecb458aa8c2f99aa6fb6285":{
      "scriptId":"u37"},
    "425c0ee90bd749d0aee96d0f8ea48848":{
      "scriptId":"u38"},
    "b978aa338cd84e2fbce6792fe71e60ce":{
      "scriptId":"u39"},
    "6c1938598cd44084ac1512eb9ff4aca1":{
      "scriptId":"u40"},
    "387445aa9cd04c9a855d77175243eb78":{
      "scriptId":"u41"},
    "978870c789494d07ab14fb3c7a716205":{
      "scriptId":"u42"},
    "c83f67a454c64407b3285c63e624d207":{
      "scriptId":"u43"},
    "459f2d8031c242d5b1d57e077d2ac330":{
      "scriptId":"u44"},
    "f904b3bec3624ddbaebd49ecb9ed4ff9":{
      "scriptId":"u45"},
    "9b5938256b3042f8b674d7cdb9812f0f":{
      "scriptId":"u46"},
    "16be25b509dd47e08c371ccd31237cdf":{
      "scriptId":"u47"},
    "843403c8d36d40a8a50f53a70f357f79":{
      "scriptId":"u48"},
    "376199f08af1443f8da3951aedd9c287":{
      "scriptId":"u49"},
    "0a2d88eac49c4b2bb189fd6ff49e84dd":{
      "scriptId":"u50"},
    "65b49b7f722646d5bc6fd9f8017b6ad9":{
      "scriptId":"u51"},
    "eea7b431c55548459d9f380482e69566":{
      "scriptId":"u52"},
    "27f7ee264c7343dfab008f6239885fed":{
      "scriptId":"u53"},
    "137039dc944e4296877a6a772b9b57b0":{
      "scriptId":"u54"},
    "320679549c98435d97a40d55caa599cb":{
      "scriptId":"u55"},
    "4ce7920bfb384c85b7647b80fb455f81":{
      "scriptId":"u56"},
    "340d2f78b8b64d7dacfcd3026b9897b3":{
      "scriptId":"u57"},
    "7463d3755c414169a218db833f15d0db":{
      "scriptId":"u58"},
    "6fa57b2b0be146938d057573dfc577f0":{
      "scriptId":"u59"},
    "4e2847f1fb8645aeba1d62881136fef2":{
      "scriptId":"u60"},
    "e0e3f3bf2c2949a2b689122286aadbea":{
      "scriptId":"u61"},
    "6aeb8942e1e84c2d80d39e87f063de92":{
      "scriptId":"u62"},
    "aaea9b1bd66f458c8b1f80d41e167a1f":{
      "scriptId":"u63"},
    "1c2ca35a1f9d437ba60e9f3fb41538cf":{
      "scriptId":"u64"},
    "e9a30732de9647f8b7f5604892d2d9d4":{
      "scriptId":"u65"},
    "b77e6ea4a5294c3f9b054d12c324b64c":{
      "scriptId":"u66"},
    "b684ee9cc8174cc1a14b53c4c6b1ac19":{
      "scriptId":"u67"},
    "96790fccb6624e3bbb2bdb1767eb7992":{
      "scriptId":"u68"},
    "b49f5b78f9474a0abddbd4492a930be3":{
      "scriptId":"u69"},
    "c3545d0a410841d592bd786b45278c74":{
      "scriptId":"u70"},
    "5a17f9e89b424c28a95d6c4ae20ea162":{
      "scriptId":"u71"}}});